### ISSUE TITLE
Adapter is not connecting to the remocon cloud

### ISSUE THREAD

**Issue by vogi13** [marwin79/ioBroker.remotethermo#30]
First of all: many thanks for this adapter!
But I can't get it to work...

After starting the adapter, everything seems to be ok, the instance shows shortly "green" but then it can't connect to the remocon service.
The remocon objects in the ioBroker objects list are generated, but there aren't any readings or values.
The log shows:
- Login error
- Request failed with status code 500  

I double checked the account credentials (e-mail and password) and the plant ID

**Versions:**  
 - Adapter version: 0.0.1
 - JS-Controller version: 4.0.24
 - Node version: v18.5.0
 - Operating system: piOS

**Comment by marwin79** [comment]
Did you select Ariston or Remocon?

Are you able to login to https://www.remocon-net.remotethermo.com/ or https://www.ariston-net.remotethermo.com/ ?

**Comment by vogi13** [comment]
For the servicename I selected "Remocon-Net Elco" (because I have an Elco Thision Mini)

And yes, I'm able to login to both. Remocon-net and Ariston.

**Comment by marwin79** [comment]
Please generate a HAR file. Just google for "generate a har file in [add your browser name here]".

You have to remove your credentials from the HAR file, before uploading !

**Comment by vogi13** [comment]
ok... just to understand:
You want me to log in to the https://www.remocon-net.remotethermo.com/  
website and create a HAR file of the login process?

**Comment by marwin79** [comment]
Exactly. Just to verify if your gateway uses the same URLs for the login process.
Don't forget to remove sensitive information (username, password) from the HAR file.

**Comment by vogi13** [comment]
Perfect. Attached you will find the anonymized HAR file of the login process to remocon-net.
Thank you for reviewing it.
[www.remocon-net.har.txt](https://github.com/marwin79/ioBroker.remotethermo/files/11669238/www.remocon-net.har.txt)

**Comment by marwin79** [comment]
Looks like the the login process itself is missing, maybe you already had the session in your cookies.
But the URLs looks the same.

Just added more debug output to the adapter. Could you please install version 0.0.2, set log level to debug and send the output to me ([marc.winiger@gmail.com](mailto:marc.winiger@gmail.com))?

**Comment by vogi13** [comment]
I've send you the log file.
Thanks.
